export const mockProjects = [
  {
    id: '1',
    title: 'Midnight Betrayal',
    duration: '0:47',
    scenes: 7,
    status: 'complete',
    thumbnail: null,
    createdAt: '2 hours ago',
    platform: 'tiktok',
    views: '142K',
  },
  {
    id: '2',
    title: 'The Last Call',
    duration: '0:31',
    scenes: 5,
    status: 'rendering',
    thumbnail: null,
    createdAt: '5 hours ago',
    platform: 'instagram',
    views: null,
  },
  {
    id: '3',
    title: 'Coastal Reckoning',
    duration: '0:58',
    scenes: 9,
    status: 'draft',
    thumbnail: null,
    createdAt: 'Yesterday',
    platform: 'youtube',
    views: null,
  },
  {
    id: '4',
    title: 'Red Room',
    duration: '0:22',
    scenes: 4,
    status: 'complete',
    thumbnail: null,
    createdAt: '3 days ago',
    platform: 'tiktok',
    views: '89K',
  },
]

export const mockScenes = [
  {
    id: 1,
    index: 1,
    total: 7,
    timeStart: '0:00',
    timeEnd: '0:08',
    emotion: 'Dread',
    emotionColor: '#7C5CFF',
    intensity: 91,
    text: 'The message came at 3am. She already knew before she opened it.',
    visualIntent: 'Dark bedroom, phone screen glow, shadows crawling the wall.',
    clip: 'Abandoned hotel corridor, flickering light',
    clipMatch: 95,
    motion: 'Slow Push-In',
    transition: 'Cross Dissolve',
  },
  {
    id: 2,
    index: 2,
    total: 7,
    timeStart: '0:08',
    timeEnd: '0:15',
    emotion: 'Shock',
    emotionColor: '#D64545',
    intensity: 88,
    text: 'Three words. That was all it took to end seven years.',
    visualIntent: 'Extreme close-up: shaking hands, cracked phone screen.',
    clip: 'Hands dropping coffee mug, slow motion',
    clipMatch: 87,
    motion: 'Zoom Out Fast',
    transition: 'Hard Cut',
  },
  {
    id: 3,
    index: 3,
    total: 7,
    timeStart: '0:15',
    timeEnd: '0:21',
    emotion: 'Numbness',
    emotionColor: '#9CA3AF',
    intensity: 64,
    text: 'She sat on the bathroom floor until the tile went cold.',
    visualIntent: 'Empty hallway, dim bathroom light, rain on window.',
    clip: 'Rain-streaked window, interior shot',
    clipMatch: 91,
    motion: 'Static Hold',
    transition: 'Fade to Black',
  },
  {
    id: 4,
    index: 4,
    total: 7,
    timeStart: '0:21',
    timeEnd: '0:34',
    emotion: 'Betrayal',
    emotionColor: '#D64545',
    intensity: 82,
    text: "She found the phone he swore didn't exist.",
    visualIntent: 'Dark car interior, phone glow, night tension.',
    clip: 'Car interior, dashboard light, night driving',
    clipMatch: 92,
    motion: 'Slow Push-In',
    transition: 'Hard Cut',
  },
  {
    id: 5,
    index: 5,
    total: 7,
    timeStart: '0:34',
    timeEnd: '0:41',
    emotion: 'Rage',
    emotionColor: '#D64545',
    intensity: 97,
    text: 'Every lie. Every alibi. Every tender moment. Staged.',
    visualIntent: 'Handheld chaos, red tint, shattered glass.',
    clip: 'Broken mirror close-up, red filter',
    clipMatch: 89,
    motion: 'Shake + Zoom',
    transition: 'Glitch Cut',
  },
  {
    id: 6,
    index: 6,
    total: 7,
    timeStart: '0:41',
    timeEnd: '0:47',
    emotion: 'Resolve',
    emotionColor: '#D6B36A',
    intensity: 76,
    text: 'She packed one bag. She never looked back.',
    visualIntent: 'Silhouette in doorway, golden hour, freedom.',
    clip: 'Woman silhouette against sunset, wide shot',
    clipMatch: 94,
    motion: 'Pull Back Wide',
    transition: 'Fade Out',
  },
]

export const mockStyles = [
  { id: 'noir', name: 'Noir Cinéma', desc: 'High contrast shadows, cold blue tones, slow burns', tag: 'Drama' },
  { id: 'golden', name: 'Golden Hour', desc: 'Warm cinematic tones, lens flares, emotional depth', tag: 'Romance' },
  { id: 'rage', name: 'Red Rage', desc: 'Saturated reds, handheld chaos, aggressive cuts', tag: 'Thriller' },
  { id: 'ghost', name: 'Ghost Signal', desc: 'Glitch artifacts, digital noise, surveillance feel', tag: 'Horror' },
  { id: 'drift', name: 'Coastal Drift', desc: 'Desaturated blues, ocean ambience, melancholy pace', tag: 'Drama' },
  { id: 'neon', name: 'Neon Void', desc: 'Cyberpunk palette, violet and magenta, rain-slicked streets', tag: 'Sci-Fi' },
]

export const mockTranscript = [
  { id: 1, start: '0:00', text: 'The message came at 3am.' },
  { id: 2, start: '0:03', text: 'She already knew before she opened it.' },
  { id: 3, start: '0:08', text: 'Three words.' },
  { id: 4, start: '0:10', text: 'That was all it took to end seven years.' },
  { id: 5, start: '0:15', text: 'She sat on the bathroom floor until the tile went cold.' },
  { id: 6, start: '0:21', text: "She found the phone he swore didn't exist." },
  { id: 7, start: '0:28', text: 'Every lie. Every alibi.' },
  { id: 8, start: '0:31', text: 'Every tender moment. Staged.' },
  { id: 9, start: '0:34', text: 'Every lie. Every alibi. Every tender moment. Staged.' },
  { id: 10, start: '0:41', text: 'She packed one bag. She never looked back.' },
]

export const mockMotionPresets = [
  { id: 'push', name: 'Slow Push-In', icon: '→', desc: 'Creeping forward momentum' },
  { id: 'pullback', name: 'Pull Back Wide', icon: '←', desc: 'Reveal the full scene' },
  { id: 'zoomfast', name: 'Zoom Out Fast', icon: '⊞', desc: 'Sudden impact reveal' },
  { id: 'shake', name: 'Shake + Zoom', icon: '⚡', desc: 'Handheld chaos energy' },
  { id: 'static', name: 'Static Hold', icon: '⊡', desc: 'Cold, unblinking tension' },
  { id: 'drift', name: 'Gentle Drift', icon: '~', desc: 'Melancholy float' },
]

export const mockTransitionPresets = [
  { id: 'cut', name: 'Hard Cut', desc: 'Abrupt, aggressive' },
  { id: 'dissolve', name: 'Cross Dissolve', desc: 'Soft emotional blend' },
  { id: 'fade', name: 'Fade to Black', desc: 'Heavy ending weight' },
  { id: 'glitch', name: 'Glitch Cut', desc: 'Digital disorientation' },
  { id: 'whip', name: 'Whip Pan', desc: 'Kinetic energy shift' },
  { id: 'match', name: 'Match Cut', desc: 'Thematic visual bridge' },
]

export const mockCaptions = [
  { id: 1, text: 'The message came at 3am.', start: '0:00', style: 'bold-center' },
  { id: 2, text: 'She already knew.', start: '0:04', style: 'italic-bottom' },
  { id: 3, text: 'THREE WORDS.', start: '0:08', style: 'impact-top' },
  { id: 4, text: 'Seven years. Gone.', start: '0:10', style: 'bold-center' },
]
